version: '3.1'
services:
  crontab_demo:
    image: golang:1.14
    container_name: go_crontab_demo
    restart: always
    volumes:
      - ./:/root/
    working_dir: /root/
    command: /root/crontab
    environment:
    - TZ=Asia/Taipei